apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kissankonnect-pvc
  namespace: "2401152"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kissankonnect-deployment
  namespace: "2401152"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kissankonnect
  template:
    metadata:
      labels:
        app: kissankonnect
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: kissankonnect-container
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401152/kissankonnect:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kissankonnect-service
  namespace: "2401152"
spec:
  selector:
    app: kissankonnect
  ports:
    - port: 80
      targetPort: 80
