apiVersion: apps/v1
kind: Deployment
metadata:
  name: kissankonnect-app
  namespace: 2401152
  labels:
    app: kissankonnect-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kissankonnect-app

  template:
    metadata:
      labels:
        app: kissankonnect-app

    spec:
      containers:
        - name: kissankonnect-app
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401152/kissankonnect:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80   # PHP/Apache container uses port 80

          env:
            - name: APP_ENV
              value: "production"

          # liveness probe
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15

          # readiness probe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kissankonnect-service
  namespace: 2401152
  labels:
    app: kissankonnect-app

spec:
  selector:
    app: kissankonnect-app

  type: ClusterIP

  ports:
    - name: http
      port: 80
      targetPort: 80
